# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- fastlane

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(certificate)'
    certPwd: '$(certificate_pw)'
    keychain: 'temp'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(profile_dev)'
    removeProfile: false
- task: CmdLine@2
  inputs:
    script: 'fastlane test'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(profile_appstore)'
    removeProfile: false
- task: CmdLine@2
  inputs:
    script: 'fastlane build_and_upload'

