# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- azure-pipelines

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: "xcodebuild -project ItalianPlumber.xcodeproj -scheme $(scheme) -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3' test"

