default: &default
  PROJECT_NAME: 'ItalianPlumber'
  SCHEME: 'ItalianPlumber'
  BUNDLE_ID: 'com.bszamody.ItalianPlumber'

steps:
  - label: 'Test Build'
    branches: 'code-climate'
    command: 'source ~/.bashrc && bundle exec fastlane test'
    env:
      <<: *default
    agents:
      ios: 'build'
