default: &default
  PROJECT_NAME: 'ItalianPlumber'
  SCHEME: 'ItalianPlumber'
  BUNDLE_ID: 'com.bszamody.ItalianPlumber'

steps:
  - label: 'Test Build'
    branches: 'code-climate'
    command: 
      - "source ~/.bashrc && fastlane test"
      - "ls xml_report"
      - "buildkite-agent artifact upload xml_report/cobertura.xml"
    env:
      <<: *default
    agents:
      ios: 'build'
