default: &default
  PROJECT_NAME: 'ItalianPlumber'
  SCHEME: 'ItalianPlumber'
  BUNDLE_ID: 'com.bszamody.ItalianPlumber'

steps:
  - label: 'Run Tests'
    branches: 'code-climate'
    command: 
      - "echo --- :fastlane: running test"
      - "source ~/.bashrc && fastlane test"
      - "echo --- :codeclimate: generating and uploading coverage results"
      - "buildkite-agent artifact upload coverage_report/cobertura.xml"
    env:
      <<: *default
    agents:
      ios: 'build'

  - label: 'Code Climate'
    branches: 'code-climate'
    command:
      - "echo --- :codeclimate: Download Coverage results"
      - "mkdir -p coverage_report"
      - "ls"
      - "buildkite-agent artifact download coverage_report/* coverage_report/"

    env:
      <<: *default
    agents: 
      ios: 'build'
