default: &default
  PROJECT_NAME: 'ItalianPlumber'
  SCHEME: 'ItalianPlumber'
  BUNDLE_ID: 'com.bszamody.ItalianPlumber'

steps:
  - label: 'Test Build'
    branches: 'code-climate'
    command: 
      - "echo --- :fastlane: running test"
      - "source ~/.bashrc && fastlane test"
      - "echo --- :codeclimate: generating and uploading coverage results"
      - "buildkite-agent artifact upload xml_report/cobertura.xml"
    env:
      <<: *default
    agents:
      ios: 'build'

  - label: 'Code Climate'
    branches: 'code-climate'
    command:
      - "echo --- :codeclimate: Download Coverage results"
    env:
      <<: *default
    agents: 
      ios: 'build'
